---
- name: dicom_router
  hosts: vagrant

  vars:
    # Wipes DB, useful if rebuilding from scratch after a failed build
    # ALLOW_CLEAN: True

    # Send a notification to a Slack channel
    # NOTIFY: True
#  vars_files:
#    - secrets.yml  # Credentials

  roles:
    - role: orthanc
      tags: router
      name: peer-router
      settings:
        orthanc:
          ports:
            dicom: 4105
            http:  4085
          destinations:   # Peer destinations are looked up in the orthanc_peer list
            - type: peer
              dest: sample-peer

    - role: orthanc
      tags: router
      name: dicom-router
      settings:
        orthanc:
          ports:
            dicom: 4106
            http:  4086
          destinations:   # DICOM destinations are looked up in the dicom_peer list
           - type: dicom
             dest: sample-modality

    - role: orthanc
      tags: router
      name: multiplexer
      settings:
        orthanc:
          ports:
            dicom: 4107
            http:  4087
          destinations:
            - type: peer
              dest: peer-router
            - type: peer
              dest: dicom-router

#    - role: remote_logging

  post_tasks:
    - name: Notify Slack that the servers have been updated
      local_action: >
        slack
        token={{ credentials.slack.token }}
        msg="MIIP DICOM router `{{ inventory_hostname }}` configured"
      when: NOTIFY is defined and NOTIFY and credentials.slack.token is defined