---
- name: "Setup orthanc db in postgres"
  postgresql_db: "name={{settings.orthanc.db_name}}
                 state=present
                 login_host=localhost
                 port={{settings.postgres.ports.sql}}
                 login_user={{credentials.postgres.db_user}}
                 login_password={{credentials.postgres.db_pword}}"

- name: "Setup orthanc user for db in postgres"
  postgresql_user: "db={{settings.orthanc.db_name}}
                   name={{credentials.orthanc.db_user}}
                   password={{credentials.orthanc.db_pword}}
                   state=present
                   login_host=localhost
                   port={{settings.postgres.ports.sql}}
                   login_user={{credentials.postgres.db_user}}
                   login_password={{credentials.postgres.db_pword}}"

- name: "Add host mapped directories"
  sudo: True
  file: path={{ item }} state=directory owner={{ansible_user_id}}
  with_items:
    - "{{ settings.orthanc.paths.logs }}"
    - "{{ settings.orthanc.paths.data }}"

- name: "Create orthanc config"
  sudo: True
  template: >
    src=templates/orthanc.json.j2
    dest={{ settings.orthanc.paths.data }}/orthanc.json
  notify: restart_orthanc

- meta: flush_handlers

- name: "Launch orthanc container"
  docker_container:
    name: orthanc
    image: jodogne/orthanc-plugins
    # On RHEL, this _may_ need to be ["--logdir...", "config.json"]
    command: "--logdir=/var/log/orthanc /etc/orthanc/orthanc.json"
    volumes:
      - "{{settings.orthanc.paths.data}}/orthanc.json:/etc/orthanc/orthanc.json:ro"
      - "{{settings.orthanc.paths.data}}/db:/var/lib/orthanc/db"
      - "{{settings.orthanc.paths.logs}}:/var/log/orthanc"
    links:
      - db:postgres
    ports:
      - "{{settings.orthanc.ports.http}}:8042"
      - "{{settings.orthanc.ports.dicom}}:4242"