---
name: "orthanc"

settings:
  orthanc:
    title: 'Orthanc'
    aet: ORTHANC
    db_name: '{{ name }}'
    paths:
      data:  '/var/lib/{{ name }}'
      logs:  '/var/log/{{ name }}'
    ports:
      dicom: 4104
      http:  4080

credentials:
  orthanc:
    db_user: "orthanc"
    db_pword: "passw0rd"

    users:
      orthanc: "passw0rd"

  dicom_modalities:
    sample-modality: ['SAMPLE_AE', 'sample', 104]

  orthanc_peers:
    sample-peer: ['http://sample:4280', 'orthanc', 'passw0rd']