---
name: "orthanc"

settings:
  orthanc:
    title: 'Orthanc'
    aet: ORTHANC
    db_name: '{{ name }}'
    paths:
      data:  '/var/lib/{{ name }}'
      logs:  '/var/log/{{ name }}'
    ports:
      dicom: 4104
      http:  4080

credentials:
  orthanc:
    db_user: "orthanc"
    db_pword: "passw0rd"

    users:
      orthanc: "passw0rd"

  dicom_modalities:
    sample_modality: [SAMPLE_AE, sample_host, sample_port]

  orthanc_peers:
    sample_peer: ['sample_host:sample_port', 'orthanc', 'passw0rd']