---
- name: "Setup orthanc db in postgres"
  postgresql_db: "name={{settings.orthanc.db_name}}
                 state=present
                 login_host=localhost
                 port={{ports.postgres.sql}}
                 login_user={{credentials.postgres.db_user}}
                 login_password={{credentials.postgres.db_pword}}"

- name: "Setup orthanc user for db in postgres"
  postgresql_user: "db={{settings.orthanc.db_name}}
                   name={{credentials.orthanc.db_user}}
                   password={{credentials.orthanc.db_pword}}
                   state=present
                   login_host=localhost
                   port={{ports.postgres.sql}}
                   login_user={{credentials.postgres.db_user}}
                   login_password={{credentials.postgres.db_pword}}"

- name: "Add host mapped directories"
  sudo: True
  file: path={{ item }} state=directory owner={{ansible_user_id}}
  with_items:
    - "{{ settings.orthanc.log_dir }}"
    - "{{ settings.orthanc.data_dir }}"

- name: "Create orthanc config"
  sudo: True
  template: >
    src=templates/orthanc.json.j2
    dest={{ settings.orthanc.data_dir }}/orthanc.json
  notify: restart_orthanc

- meta: flush_handlers

- name: "Launch orthanc container"
  docker_container:
    name: orthanc
    image: jodogne/orthanc-plugins
    command: ["--logdir=/var/log/orthanc", "/etc/orthanc/orthanc.json"]
    volumes:
      - "{{settings.orthanc.data_dir}}/orthanc.json:/etc/orthanc/orthanc.json:ro"
      - "{{settings.orthanc.data_dir}}/db:/var/lib/orthanc/db"
      - "{{settings.orthanc.log_dir}}:/var/log/orthanc"
    links:
      - db:postgres
    ports:
      - "{{ports.orthanc.html}}:8042"
      - "{{ports.orthanc.dicom}}:4242"