---
- name: "Launch postgres container"
  docker:
    name: db
    image: postgres
    env:
      POSTGRES_USER: "{{credentials.postgres.db_user}}"
      POSTGRES_PASSWORD: "{{credentials.postgres.db_pword}}"
    ports:
      - "{{settings.postgres.ports.sql}}:5432"

- name: "Wait for postgres"
  wait_for: port={{settings.postgres.ports.sql}} delay=3

